---
- name: Install required roles
  hosts: all
  roles:
    - nl2go.openjdk

- name: Install ZooKeeper
  hosts: zookeeper
  vars:
    zookeeper_version: 3.6.2
    zookeeper_members: "{{ groups['zookeeper'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
  roles:
    - nl2go.zookeeper

- name: Prepare Kafka client
  hosts: kafka
  tasks:
    - name: Create Kafka JAAS client config
      copy:
        content: |
          KafkaClient {
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username="{{ kafka_client_users[0].username }}"
            password="{{ kafka_client_users[0].password }}";
          };
        dest: "{{ kafka_test_client_sasl_conf }}"
    - name: Create Kafka client config
      copy:
        content: |
          security.protocol=SASL_PLAINTEXT
          sasl.mechanism=PLAIN
        dest: "{{ kafka_test_client_conf }}"

- name: Download JMX CLI
  hosts: kafka
  tasks:
    - name: Download jmxterm
      get_url:
        url: https://github.com/jiaqi/jmxterm/releases/download/v1.0.1/jmxterm-1.0.1-uber.jar
        dest: /opt/jmxterm.jar
        mode: '0755'
